name: 'Scorecard Scan'
description: 'Run OSSF scorecard'
inputs:
  gh_token:
    description: 'GitHub token for authentication'
    required: true
outputs:
  results_file_path:
    description: 'Absolute path to the SARIF results file'
    value: ${{ steps.set_sarif_file_path_output.outputs.sarif_file_path }}
runs:
  using: 'composite'
  steps:
    - name: "Run scorecard"
      uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a
      with:
        results_file: results.sarif
        results_format: sarif
        publish_results: false
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
    - name: "Set SARIF file path output"
      id: set_sarif_file_path_output
      run: echo "sarif_file_path=${{ github.workspace }}/results.sarif" >> $GITHUB_OUTPUT
      shell: bash
