name: 'Scorecard Scan'
description: 'Run OSSF scorecard'
runs:
  using: 'composite'
  steps:
    - name: "Run scorecard"
      uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a
      with:
        results_file: results.sarif
        results_format: sarif
        publish_results: false
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
