name: 'Semgrep Scan'
description: 'Run Semgrep scan with custom rules and output results'
inputs:
  results_format:
    description: 'Format of the results file (json or sarif)'
    required: false
    default: 'json'
  show_results_in_pr:
    description: 'Show results in PR (true/false)'
    required: false
    default: 'true'
outputs:
  results_file_path:
    description: 'Absolute path to the Semgrep results file'
    value: ${{ steps.set_results_file_path_output.outputs.results_file_path }}
runs:
  using: 'composite'
  steps:
    - name: "Fetch semgrep rules"
      run: |
        git clone https://github.com/trailofbits/semgrep-rules $HOME/semgrep-rules-tob
        git clone https://github.com/semgrep/semgrep-rules $HOME/semgrep-rules
        git -C $HOME/semgrep-rules reset --hard 518f71b883d431fa33268844b066033507e7c1b5
        git -C $HOME/semgrep-rules-tob reset --hard 3b91c9b622b4a250b144a832ce73091b1f25e207
        rm $HOME/semgrep-rules-tob/.github/workflows/update-semgrep-registry.yml
        rm $HOME/semgrep-rules/.pre-commit-config.yaml
        rm -rf $HOME/semgrep-rules-tob/.github
        rm -rf $HOME/semgrep-rules/.github
        rm -rf $HOME/semgrep-rules/stats
      shell: bash
    - name: "Setup git repo"
      run: git config --global --add safe.directory $(pwd)
      shell: bash
    - name: "Run semgrep"
      run: |
        results_file="/tmp/semgrep-results.${{ inputs.results_format }}"
        baseline_commit_arg=""
        if [ "${{ inputs.show_results_in_pr }}" = "true" ]; then
          baseline_commit_arg="--baseline-commit=${{ github.event.pull_request.base.sha }}"
        fi
        semgrep scan --config $HOME/semgrep-rules --config $HOME/semgrep-rules-tob \
          --metrics=off --experimental \
          --exclude-rule=third-party-action-not-pinned-to-commit-sha \
          --exclude-rule=jsx-not-internationalized \
          --severity=WARNING \
          --severity=ERROR \
          --exclude="*.html" --exclude="*.js" --exclude="*.spec.ts" \
          $baseline_commit_arg \
          --${{ inputs.results_format }} | \
          jq 'to_entries | map(if .key == "results" then .value |= map(select(.extra.metadata.confidence != "LOW")) else . end) | from_entries' \
          > "$results_file" || true
      shell: bash
    - name: "Set results file path output"
      id: set_results_file_path_output
      run: echo "results_file_path=/tmp/semgrep-results.${{ inputs.results_format }}" >> $GITHUB_OUTPUT
      shell: bash
    - name: "Show results in PR"
      if: ${{ inputs.show_results_in_pr == 'true' && inputs.results_format == 'json' }}
      run: |
        /usr/bin/jq -r '.results[]
          | . + {
              severity: (
                if .extra.severity == "WARNING" then "warning"
                elif .extra.severity == "ERROR" then "error"
                else "notice"
                end
              )
            }
          | "::\(.severity) file=\(.path),line=\(.start.line),col=\(.start.col),endLine=\(.end.line),endColumn=\(.end.col),title=\(.check_id)::\((.extra.message
              | gsub("[^a-zA-Z0-9 .]"; "")
          ))"' /tmp/semgrep-results.json
      shell: bash
