on:
  pull_request:

name: Semgrep scan

permissions:
  contents: read

jobs:
  semgrep:
    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')
    name: semgrep-oss/scan
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps:
      - uses: actions/checkout@v3
      - run: |
         git clone https://github.com/trailofbits/semgrep-rules $HOME/semgrep-rules-tob
         git clone https://github.com/semgrep/semgrep-rules $HOME/semgrep-rules
         git -C $HOME/semgrep-rules reset --hard d1ac184a1eca88c71291ce29972ff46ea23547dc
         git -C $HOME/semgrep-rules-tob reset --hard cfff2e18a95c244691ee1b6493e39e3eda9354ef
         rm $HOME/semgrep-rules-tob/.github/workflows/update-semgrep-registry.yml
         rm $HOME/semgrep-rules/.pre-commit-config.yaml
         rm -rf $HOME/semgrep-rules-tob/.github
         rm -rf $HOME/semgrep-rules/.github
         rm -rf $HOME/semgrep-rules/stats
      - run: git config --global --add safe.directory $(pwd)
      - run: |
          semgrep scan --config $HOME/semgrep-rules --config $HOME/semgrep-rules-tob \
            --metrics=off --experimental \
            --exclude-rule=yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha \
            --exclude-rule=ai.generic.detect-generic-ai-anthprop.detect-generic-ai-anthprop \
            --exclude-rule=ai.generic.detect-generic-ai-api.detect-generic-ai-api \
            --exclude-rule=ai.generic.detect-generic-ai-gem.detect-generic-ai-gem \
            --exclude-rule=ai.generic.detect-generic-ai-oai.detect-generic-ai-oai \
            --exclude="*.html" --exclude="*.js" \
            --sarif --sarif-output=semgrep-results.sarif || true
      - name: Save SARIF results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-scan-results
          path: semgrep-results.sarif
        if: always()
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: semgrep-results.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: semgrep
        if: always()


